// <auto-generated />
using System;
using JournalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JournalApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JournalApp.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMood1")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMood2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("JournalApp.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "System",
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Category = "System",
                            Name = "Career"
                        },
                        new
                        {
                            Id = 3,
                            Category = "System",
                            Name = "Studies"
                        },
                        new
                        {
                            Id = 4,
                            Category = "System",
                            Name = "Family"
                        },
                        new
                        {
                            Id = 5,
                            Category = "System",
                            Name = "Friends"
                        },
                        new
                        {
                            Id = 6,
                            Category = "System",
                            Name = "Relationships"
                        },
                        new
                        {
                            Id = 7,
                            Category = "System",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 8,
                            Category = "System",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 9,
                            Category = "System",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 10,
                            Category = "System",
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 11,
                            Category = "System",
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 12,
                            Category = "System",
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 13,
                            Category = "System",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 14,
                            Category = "System",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            Category = "System",
                            Name = "Reflection"
                        });
                });

            modelBuilder.Entity("JournalApp.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDarkMode = false,
                            Pin = "1234"
                        });
                });

            modelBuilder.Entity("JournalEntryTag", b =>
                {
                    b.Property<int>("EntriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntriesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("JournalEntryTag");
                });

            modelBuilder.Entity("JournalEntryTag", b =>
                {
                    b.HasOne("JournalApp.Models.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("EntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JournalApp.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
